In [1]:
print('Class NP and Panda')

Class NP and Panda


In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt


In [3]:
### add 1 to every element

m= [100, 200.0, 300, 400]
print([i+1 for i  in m])


[101, 201.0, 301, 401]


In [7]:
m= [1,2,3,4,5]
type(m)

list

In [8]:
m1= np.array(m)
m1

array([1, 2, 3, 4, 5])

In [9]:
print(m1)

[1 2 3 4 5]


In [10]:
# convert to float

m= [1,2,3,4,5.5]
m1= np.array(m)
print(m1)

[1.  2.  3.  4.  5.5]


In [11]:
## converts output to str

m= [1,2,3,4,5.5,'anurag']
m1= np.array(m)
print(m1)

['1' '2' '3' '4' '5.5' 'anurag']


In [12]:
m= [[1,2,3],[4,5,6],[7,8,9], [10,11,12]]
m1= np.array(m)
print(m1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
m1.shape

(4, 3)

In [14]:
### Numpy low>>high bool>>int>>float>>str i

In [16]:
print(m1[2][0])

7


In [17]:
## replace value

m1[2][0]= 77
print(m1)

[[ 1  2  3]
 [ 4  5  6]
 [77  8  9]
 [10 11 12]]


In [19]:
a= np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [20]:
a= np.zeros((4,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
a= np.zeros((4,3), dtype=bool)
print(a)

[[False False False]
 [False False False]
 [False False False]
 [False False False]]


In [22]:
a= np.zeros((4,3), dtype=str)
print(a)

[['' '' '']
 ['' '' '']
 ['' '' '']
 ['' '' '']]


In [24]:
a= np.ones((4,3), dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [25]:
a= np.linspace(1,10,2) ## start, stop, size
print(a)

[ 1. 10.]


In [26]:
a= np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [27]:
a= np.linspace((1,10,10),dtype= int)
print(a)

TypeError: linspace() missing 1 required positional argument: 'stop'

In [28]:
a= np.linspace(1,5,10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [29]:
a= np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
a= np.random.rand(4,3)
print(a)

[[0.08835102 0.66388201 0.36797371]
 [0.51144152 0.32823507 0.63164545]
 [0.52754708 0.74130503 0.13158963]
 [0.0876012  0.74880682 0.63204419]]


In [34]:
a= np.random.rand(9)
print(a)

[0.69420234 0.53878166 0.36149187 0.28615607 0.06565143 0.21761958
 0.15336935 0.27721518 0.5420326 ]


In [35]:
a= np.random.randint(-9,9,(4,3))
print(a)

[[-4 -3 -1]
 [-6  4 -6]
 [-6  4 -3]
 [ 1  5 -4]]


In [37]:
print(a)

[[-4 -3 -1]
 [-6  4 -6]
 [-6  4 -3]
 [ 1  5 -4]]


In [38]:
a.shape

(4, 3)

In [39]:
a2= a.reshape((6,2))
print(a2)

[[-4 -3]
 [-1 -6]
 [ 4 -6]
 [-6  4]
 [-3  1]
 [ 5 -4]]


In [40]:
a2= a.reshape((2,6))
print(a2)

[[-4 -3 -1 -6  4 -6]
 [-6  4 -3  1  5 -4]]


In [43]:
print(a2[1,0])

-6


In [44]:
print(a2[1])

[-6  4 -3  1  5 -4]


In [46]:
print(a2[:,:1])

[[-4]
 [-6]]


In [47]:
print(a2.sum())

-19


In [48]:
print(a2[:,0].sum())

-10


In [49]:
print(a2[:,1].sum())

1


In [50]:
print(a2[1,:].sum())

-3


In [52]:
print(a2.sum(axis=1))

[-16  -3]


In [53]:
print(a2.sum(axis=0))

[-10   1  -4  -5   9 -10]


In [54]:
print(a2.mean(axis=0))

[-5.   0.5 -2.  -2.5  4.5 -5. ]


In [55]:
print(a2.mean(axis=1))

[-2.66666667 -0.5       ]


In [61]:
a= np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [62]:
### Braodcasting

a1= np.arange(10)
a2=a1[:4]
print(a2)


[0 1 2 3]


In [63]:
a2[0]= -100
print(a2)

[-100    1    2    3]


In [64]:
print(a1)

[-100    1    2    3    4    5    6    7    8    9]


In [65]:
print(a1>4)

[False False False False False  True  True  True  True  True]


In [67]:
print(a1[a1>4])

[5 6 7 8 9]


In [71]:
print(max(a1[a1>4]))
print(len(a1[a1>4]))
print(min(a1[a1>4]))

9
5
5


In [89]:
b= np.arange(1,10)
print(b)
print(b[b%2==0])
print(b.shape)

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]
(9,)


In [88]:
c= np.arange(11,20)
print(c)
print(c.shape)

[11 12 13 14 15 16 17 18 19]
(9,)


In [90]:
d= b+c
print(d)


[12 14 16 18 20 22 24 26 28]


In [102]:
print(c+2)
print(c*2)
print(c-2)
print(c/2)
print(c**2)
print(c**(1/2))
print(np.log(c))
print(np.exp(c))


[13 14 15 16 17 18 19 20 21]
[22 24 26 28 30 32 34 36 38]
[ 9 10 11 12 13 14 15 16 17]
[5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[121 144 169 196 225 256 289 324 361]
[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
 4.12310563 4.24264069 4.35889894]
[2.39789527 2.48490665 2.56494936 2.63905733 2.7080502  2.77258872
 2.83321334 2.89037176 2.94443898]
[5.98741417e+04 1.62754791e+05 4.42413392e+05 1.20260428e+06
 3.26901737e+06 8.88611052e+06 2.41549528e+07 6.56599691e+07
 1.78482301e+08]


In [106]:
a= np.arange(11)
print(a)
print(a*a)
print(a/a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[  0   1   4   9  16  25  36  49  64  81 100]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\Pallav\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [107]:
print(np.nan)


nan


In [108]:
print(1==1)

True


In [112]:
print(np.nan== np.nan)

False


In [116]:
print(np.where(c==17))

(array([6], dtype=int64),)


In [121]:
a= np.random.randint(-50,50,(10))
print(a)
print(sort(a))
print()

[  0 -38  48 -16  39   8 -45 -38 -28  -1]


In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
from random import seed
from random import randint

In [3]:
#### PANDAS####

print("Class Pandas 31-07-2022")


Class Pandas 31-07-2022


In [7]:
l= [10,20,30]
s= pd.Series(l)
s

0    10
1    20
2    30
dtype: int64

In [6]:
type(s)

pandas.core.series.Series

In [9]:
s1= pd.Series(l, index= ['a','b','c'])
s1


a    10
b    20
c    30
dtype: int64

In [10]:
d= {'a':10,'b':20,'c':30}
d1= pd.Series(d)
d1

a    10
b    20
c    30
dtype: int64

In [14]:
type(d1.index)

pandas.core.indexes.base.Index

In [16]:
d= {'a':10,'b':20,'c':30}
d1= np.array(d)
d2= pd.Series(d1)
d2

0    {'a': 10, 'b': 20, 'c': 30}
dtype: object

In [17]:
l= [10,20,30]
s= np.array(l)
s1= pd.Series(s)
s1

0    10
1    20
2    30
dtype: int32

In [20]:
l1= [10,'20',30.0, True]
l2= pd.Series(l1)
print(l2)

0      10
1      20
2      30
3    True
dtype: object


In [19]:
type(l2)

pandas.core.series.Series

In [27]:
l1= [10,'20',30.0, True]
l2=pd.Series(l1)
print(l2[2])
print(l2[1:])
print(l2.iloc[-2])
print(l2)

30.0
1      20
2      30
3    True
dtype: object
30.0
0      10
1      20
2      30
3    True
dtype: object


In [29]:
print(l2+l2)

0      20
1    2020
2      60
3       2
dtype: object


In [34]:
l = [1,2,3]
s= [4,5,6]
l1= pd.Series(l)
s1= pd.Series(s)
print(l1)
print(s1)


0    1
1    2
2    3
dtype: int64
0    4
1    5
2    6
dtype: int64


In [36]:
print(l1+s1)
print(l1*s1)
print(l1**s1)

0    5
1    7
2    9
dtype: int64
0     4
1    10
2    18
dtype: int64
0      1
1     32
2    729
dtype: int64


In [37]:
### DATA FRAme

a= np.random.rand(5,4)
print(a)

[[0.19875264 0.33366817 0.52636596 0.62873472]
 [0.92325978 0.05221065 0.6146598  0.50900073]
 [0.27660507 0.9632423  0.50630831 0.78950978]
 [0.91235421 0.99970258 0.84810494 0.4129423 ]
 [0.3165645  0.23313629 0.69649068 0.15231028]]


In [38]:
a1= pd.DataFrame(a)
a1

0         1         2         3
0  0.198753  0.333668  0.526366  0.628735
1  0.923260  0.052211  0.614660  0.509001
2  0.276605  0.963242  0.506308  0.789510
3  0.912354  0.999703  0.848105  0.412942
4  0.316564  0.233136  0.696491  0.152310

In [39]:
a2= pd.DataFrame(a, index= 'a b c d e'.split(), columns= '1 2 3 4'.split())
print(a2)

          1         2         3         4
a  0.198753  0.333668  0.526366  0.628735
b  0.923260  0.052211  0.614660  0.509001
c  0.276605  0.963242  0.506308  0.789510
d  0.912354  0.999703  0.848105  0.412942
e  0.316564  0.233136  0.696491  0.152310


In [42]:
print(a2.loc['b'][2])

0.6146598014352329


In [43]:
print(max(a2))

4


In [61]:
a3= pd.DataFrame(a, index= 'a b c d e'.split(), columns= 'c1 c2 c3 c4'.split())
a3

c1        c2        c3        c4
a  0.198753  0.333668  0.526366  0.628735
b  0.923260  0.052211  0.614660  0.509001
c  0.276605  0.963242  0.506308  0.789510
d  0.912354  0.999703  0.848105  0.412942
e  0.316564  0.233136  0.696491  0.152310

In [59]:
a3['c5']= a3['c2']+ a3['c3']
a3

c1        c2        c3        c4        c5
a  0.198753  0.333668  0.526366  0.628735  0.860034
b  0.923260  0.052211  0.614660  0.509001  0.666870
c  0.276605  0.963242  0.506308  0.789510  1.469551
d  0.912354  0.999703  0.848105  0.412942  1.847808
e  0.316564  0.233136  0.696491  0.152310  0.929627

In [58]:
a4=a3.drop('c3', axis=1)
a4

c1        c2        c4        c5
a  0.198753  0.333668  0.628735  0.860034
b  0.923260  0.052211  0.509001  0.666870
c  0.276605  0.963242  0.789510  1.469551
d  0.912354  0.999703  0.412942  1.847808
e  0.316564  0.233136  0.152310  0.929627

In [56]:
a3

c1        c2        c3        c4        c5
a  0.198753  0.333668  0.526366  0.628735  0.860034
b  0.923260  0.052211  0.614660  0.509001  0.666870
c  0.276605  0.963242  0.506308  0.789510  1.469551
d  0.912354  0.999703  0.848105  0.412942  1.847808
e  0.316564  0.233136  0.696491  0.152310  0.929627

In [67]:
a3.reset_index(drop=True)

c1        c2        c3        c4
0  0.198753  0.333668  0.526366  0.628735
1  0.923260  0.052211  0.614660  0.509001
2  0.276605  0.963242  0.506308  0.789510
3  0.912354  0.999703  0.848105  0.412942
4  0.316564  0.233136  0.696491  0.152310

In [72]:
b= input()
c= b.count('a')
d= b.count('e')
print(c)
print(d)

abcabcdef'
2
1


In [73]:
b= input()
c= b.count('python')
print(c)

"anurag is learning python
1


In [79]:
a4=a3[a3>0.3]
a4

c1        c2        c3        c4
a       NaN  0.333668  0.526366  0.628735
b  0.923260       NaN  0.614660  0.509001
c       NaN  0.963242  0.506308  0.789510
d  0.912354  0.999703  0.848105  0.412942
e  0.316564       NaN  0.696491       NaN

In [78]:
a4.dropna()

Empty DataFrame
Columns: [c1, c2, c3, c4]
Index: []

In [80]:
a4.isna()

c1     c2     c3     c4
a   True  False  False  False
b  False   True  False  False
c   True  False  False  False
d  False  False  False  False
e  False   True  False   True

In [81]:
a4.dropna(thresh=2)


c1        c2        c3        c4
a       NaN  0.333668  0.526366  0.628735
b  0.923260       NaN  0.614660  0.509001
c       NaN  0.963242  0.506308  0.789510
d  0.912354  0.999703  0.848105  0.412942
e  0.316564       NaN  0.696491       NaN

In [82]:
a4.fillna(value=0)

c1        c2        c3        c4
a  0.000000  0.333668  0.526366  0.628735
b  0.923260  0.000000  0.614660  0.509001
c  0.000000  0.963242  0.506308  0.789510
d  0.912354  0.999703  0.848105  0.412942
e  0.316564  0.000000  0.696491  0.000000

In [83]:
a4.fillna(value= a4.mean())

c1        c2        c3        c4
a  0.717393  0.333668  0.526366  0.628735
b  0.923260  0.765538  0.614660  0.509001
c  0.717393  0.963242  0.506308  0.789510
d  0.912354  0.999703  0.848105  0.412942
e  0.316564  0.765538  0.696491  0.585047

In [85]:
d = {'Country':['in','in','cn','us','cn'],'Flag':['A','B','A','B','A'],'Score':[1,2,3,2,1]}
df = pd.DataFrame(d)
df

Country Flag  Score
0      in    A      1
1      in    B      2
2      cn    A      3
3      us    B      2
4      cn    A      1

In [88]:
df.Country.unique()

array(['in', 'cn', 'us'], dtype=object)

In [90]:
df.Country.nunique()

3

In [91]:
df.Country.value_counts()

cn    2
in    2
us    1
Name: Country, dtype: int64

In [92]:
df.sort_values('Score', ascending= False)


Country Flag  Score
2      cn    A      3
1      in    B      2
3      us    B      2
0      in    A      1
4      cn    A      1

In [93]:
df.drop_duplicates('Country')

Country Flag  Score
0      in    A      1
2      cn    A      3
3      us    B      2

In [95]:
df.drop_duplicates(['Country', 'Flag'])

Country Flag  Score
0      in    A      1
1      in    B      2
2      cn    A      3
3      us    B      2

In [99]:
def sqr (x):
    return x*x

df1= df.Score.apply(sqr)
df1

0    1
1    4
2    9
3    4
4    1
Name: Score, dtype: int64

In [100]:
df['sqr']= df1
df

Country Flag  Score  sqr
0      in    A      1    1
1      in    B      2    4
2      cn    A      3    9
3      us    B      2    4
4      cn    A      1    1

In [104]:
def sum (a,b):
    return a+b

df2=df[['Score', 'sqr']].apply(lambda df: sum(a=df.Score, b=df.sqr),axis=1)

In [105]:
df['sum']= df2
df

Country Flag  Score  sqr  sum
0      in    A      1    1    2
1      in    B      2    4    6
2      cn    A      3    9   12
3      us    B      2    4    6
4      cn    A      1    1    2

In [106]:
df.describe()

Score       sqr       sum
count  5.00000  5.000000   5.00000
mean   1.80000  3.800000   5.60000
std    0.83666  3.271085   4.09878
min    1.00000  1.000000   2.00000
25%    1.00000  1.000000   2.00000
50%    2.00000  4.000000   6.00000
75%    2.00000  4.000000   6.00000
max    3.00000  9.000000  12.00000

In [108]:
d3= df.groupby('Country').sum()
d3

Score  sqr  sum
Country                 
cn           4   10   14
in           3    5    8
us           2    4    6

In [110]:
### Practice

sbi = pd.DataFrame({'aadhaarNo':["000003", "000005", "000001", "000006", "000002"],'Name': ["Tony",   "Thor",   "Natasha", "Fury", "Groot"],'Balance':  [999999,    100,      200,        300,     0]})
govt = pd.DataFrame({'identificationNo':["000001", "000002", "000003", "000004", "000005", "000006"],'Name': ["Natasha", "Groot",  "Tony",   "Tony",   "Thor",   "Fury"],'criminal': [True,       True,      True,    False,   False,    False]})



In [111]:
m= pd.merge(left= sbi, right=govt, how= 'inner', left_on='aadhaarNo', right_on='identificationNo')
m

aadhaarNo   Name_x  Balance identificationNo   Name_y  criminal
0    000003     Tony   999999           000003     Tony      True
1    000005     Thor      100           000005     Thor     False
2    000001  Natasha      200           000001  Natasha      True
3    000006     Fury      300           000006     Fury     False
4    000002    Groot        0           000002    Groot      True

In [112]:
m1= pd.merge(left= sbi, right=govt, how= 'inner', on='Name')
m1

aadhaarNo     Name  Balance identificationNo  criminal
0    000003     Tony   999999           000003      True
1    000003     Tony   999999           000004     False
2    000005     Thor      100           000005     False
3    000001  Natasha      200           000001      True
4    000006     Fury      300           000006     False
5    000002    Groot        0           000002      True