In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [8]:
## 8*8 matrix. 50th element

a= np.array(range(1, 8*8+1))


In [6]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]


In [9]:
b= a.reshape(8,8)
print(b)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [11]:
ind = np.unravel_index(49, (8,8))

print(ind)

(6, 1)


In [12]:
## first 3 row, 5 columns

print(b[:3,-5:])

[[ 4  5  6  7  8]
 [12 13 14 15 16]
 [20 21 22 23 24]]


In [13]:
print(b[:3,-6:])

[[ 3  4  5  6  7  8]
 [11 12 13 14 15 16]
 [19 20 21 22 23 24]]


In [14]:
## hows reshapw ill be

c= np.arange(1,16,2)
print(c)

[ 1  3  5  7  9 11 13 15]


In [15]:
c= np.arange(1,16,2).reshape(4,2)
print(c)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [19]:
## positive odd int >2
n= int(input())

e= np.zeros((n, n), dtype = int)

print(e)

5
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [20]:

e[n//2, :] = 1
e[: , n//2] = 1
      
print(e)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [21]:
print("Pandas Graded- Megamart sales")

Pandas Graded- Megamart sales


In [22]:
m1= pd.read_csv("MegaMart_sales.csv" , header=0)
m1.head(3)

Order ID                                Product Name  Discount  \
0  AZ-2011-1029887  Novimex Color Coded Labels, 5000 Label Set       0.0   
1   AZ-2011-107716              Deflect-O Door Stop, Erganomic       0.0   
2  AZ-2011-1087704               Belkin Flash Drive, Bluetooth       0.0   

   Sales  Profit  Quantity         Category Sub-Category  
0     26       7         2  Office Supplies       Labels  
1     85      15         2        Furniture  Furnishings  
2    294     109         7       Technology  Accessories

In [28]:
m2= pd.read_csv("MegaMart_newsales.csv" , header=0)
m2.head(3)

Order ID                         Product Name  Discount  Sales  \
0  AZ-2011-1902971  Wilson Jones Binding Machine, Clear       0.0    339   
1  AZ-2011-1916360        Dania 3-Shelf Cabinet, Mobile       0.0    288   
2  AZ-2011-1916555          Eldon Folders, Single Width       0.4     61   

   Profit  Quantity         Category Sub-Category  
0     102         7  Office Supplies      Binders  
1      20         2        Furniture    Bookcases  
2       7         6  Office Supplies      Storage

In [44]:
## Merge df and sales value

m3=m1.merge(m2, how="outer")

m3.head(3)

Order ID                                Product Name  Discount  \
0  AZ-2011-1029887  Novimex Color Coded Labels, 5000 Label Set       0.0   
1   AZ-2011-107716              Deflect-O Door Stop, Erganomic       0.0   
2  AZ-2011-1087704               Belkin Flash Drive, Bluetooth       0.0   

   Sales  Profit  Quantity         Category Sub-Category  
0     26       7         2  Office Supplies       Labels  
1     85      15         2        Furniture  Furnishings  
2    294     109         7       Technology  Accessories

In [51]:
m4= m3.groupby(by='Category').sum()
m4

Discount  Sales  Profit  Quantity
Category                                          
Furniture             1.3   2460     333        36
Office Supplies       4.7   7970    1338       169
Technology            0.0   8588    2278        60

In [48]:
## drop duplicates

m5 = m3.drop_duplicates(keep='first')
m5

Order ID                                  Product Name  Discount  \
0   AZ-2011-1029887    Novimex Color Coded Labels, 5000 Label Set       0.0   
1    AZ-2011-107716                Deflect-O Door Stop, Erganomic       0.0   
2   AZ-2011-1087704                 Belkin Flash Drive, Bluetooth       0.0   
4   AZ-2011-1372644                    Panasonic Printer, Durable       0.0   
6   AZ-2011-1362199                     Sanford Pens, Fluorescent       0.5   
..              ...                                           ...       ...   
63  AZ-2011-1967754                  Logitech Numeric Keypad, USB       0.0   
64  AZ-2011-1976919                          Boston Markers, Blue       0.0   
65  AZ-2011-2001312                  Avery Binding Machine, Clear       0.0   
66  AZ-2011-2002251     SanDisk Computer Printout Paper, 8.5 x 11       0.0   
67   AZ-2011-201891  Cameo Clasp Envelope, with clear poly window       0.0   

    Sales  Profit  Quantity         Category Sub-Category  
0      26       7         2  Office Supplies       Labels  
1      85      15         2        Furniture  Furnishings  
2     294     109         7       Technology  Accessories  
4     800     168         3       Technology     Machines  
6      25     -11         4  Office Supplies          Art  
..    ...     ...       ...              ...          ...  
63     93      40         2       Technology  Accessories  
64    132      54         5  Office Supplies          Art  
65     97      12         2  Office Supplies      Binders  
66    136      15         4  Office Supplies        Paper  
67     52      19         4  Office Supplies    Envelopes  

[61 rows x 8 columns]

In [49]:
m5.groupby(by='Category').sum()

Discount  Sales  Profit  Quantity
Category                                          
Furniture             1.3   2460     333        36
Office Supplies       3.6   6964    1045       149
Technology            0.0   7494    2001        50

In [75]:
### Best category- sub category

m6= m5.groupby(["Category","Sub-Category"]).sum()
m6.sort_values("Profit", ascending=False)

Discount  Sales  Profit  Quantity  no_of_digits
Category        Sub-Category                                                 
Technology      Phones             0.0   5199    1618        26            35
Furniture       Bookcases          0.1   1459     308        11            20
Office Supplies Art                1.0   1364     275        44            63
                Appliances         0.1   1819     229         8            13
Technology      Accessories        0.0   1053     215        18            21
Office Supplies Storage            2.0   2019     192        25            48
Technology      Machines           0.0    800     168         3             7
Office Supplies Binders            0.5    924     156        31            70
                Supplies           0.0    362     103        11            21
Furniture       Furnishings        0.0    443      74        12            34
Office Supplies Envelopes          0.0    146      35         9            13
                Labels             0.0    166      30        15            34
                Paper              0.0    136      15         4             7
                Fasteners          0.0     28      10         2             7
Technology      Copiers            0.0    442       0         3             7
Furniture       Chairs             1.2    558     -49        13            20

In [56]:
## Invalid orders- 7

m5['Order no']=m5['Order ID'].str.split('-')

m5['Order no']=m5['Order no'].apply(lambda x: x[2])

m5['no_of_digits']=m5['Order no'].apply(lambda x: len(x))

m5['no_of_digits'].value_counts()

C:\Users\Pallav\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\Pallav\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Pallav\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFr

7    54
6     7
Name: no_of_digits, dtype: int64

In [59]:
### invalid order =7 , as 7 orders have less 6 digits only valid order contain 7 digits

In [77]:
## Occurence of furniture in top 25 sales

m8=m5.sort_values(by='Sales', ascending=False)
m8=m5.iloc[:25,]

m8['Category'].value_counts()

Office Supplies    14
Furniture           7
Technology          4
Name: Category, dtype: int64

In [70]:
### And operation

m5[(m5.Sales > 250) & (m5.Profit > 50)].sort_values(by="Sales", ascending=False)

Order ID                         Product Name  Discount  Sales  \
30  AZ-2011-1410648         Nokia Smart Phone, Full Size       0.0   1908   
58   AZ-2011-176674                Hoover Microwave, Red       0.1   1667   
11  AZ-2011-1174243     Nokia Audio Dock, with Caller ID       0.0   1334   
23  AZ-2011-1322840     Motorola Headset, with Caller ID       0.0    957   
4   AZ-2011-1372644           Panasonic Printer, Durable       0.0    800   
20  AZ-2011-1406494         Fellowes Lockers, Industrial       0.1    748   
41  AZ-2011-1536006      Logitech Keyboard, Programmable       0.0    666   
33  AZ-2011-1445262          Apple Smart Phone, Cordless       0.0    636   
31   AZ-2011-144325        Bush Stackable Bookrack, Pine       0.0    630   
16  AZ-2011-1260928        Eldon File Cart, Single Width       0.1    576   
15  AZ-2011-1253407       Safco Stackable Bookrack, Pine       0.1    541   
51  AZ-2011-1672552      Binney & Smith Sketch Pad, Blue       0.0    510   
54  AZ-2011-1722024               Cisco Audio Dock, VoIP       0.0    364   
59  AZ-2011-1902971  Wilson Jones Binding Machine, Clear       0.0    339   
19   AZ-2011-130330     Office Star Chairmat, Adjustable       0.1    307   
2   AZ-2011-1087704        Belkin Flash Drive, Bluetooth       0.0    294   

    Profit  Quantity         Category Sub-Category Order no  no_of_digits  
30     820         3       Technology       Phones  1410648             7  
58     185         6  Office Supplies   Appliances   176674             6  
11     200         8       Technology       Phones  1174243             7  
23     316        12       Technology       Phones  1322840             7  
4      168         3       Technology     Machines  1372644             7  
20     283         4  Office Supplies      Storage  1406494             7  
41      66         9       Technology  Accessories  1536006             7  
33     140         1       Technology       Phones  1445262             7  
31     132         5        Furniture    Bookcases   144325             6  
16      51         5  Office Supplies      Storage  1260928             7  
15     156         4        Furniture    Bookcases  1253407             7  
51     132        11  Office Supplies          Art  1672552             7  
54     142         2       Technology       Phones  1722024             7  
59     102         7  Office Supplies      Binders  1902971             7  
19      99         5        Furniture       Chairs   130330             6  
2      109         7       Technology  Accessories  1087704             7

In [71]:
#### Column manuplation

m9 = m3[m3["Profit"]>0]
m9.head(3)

Order ID                                Product Name  Discount  \
0  AZ-2011-1029887  Novimex Color Coded Labels, 5000 Label Set       0.0   
1   AZ-2011-107716              Deflect-O Door Stop, Erganomic       0.0   
2  AZ-2011-1087704               Belkin Flash Drive, Bluetooth       0.0   

   Sales  Profit  Quantity         Category Sub-Category  order_len  
0     26       7         2  Office Supplies       Labels         15  
1     85      15         2        Furniture  Furnishings         14  
2    294     109         7       Technology  Accessories         15

In [72]:
m9=m9.loc[m9.Category=='Technology']

m9['Profit_per_qty']=m9['Profit']/m9['Quantity']

m9.sort_values(by='Profit_per_qty',ascending=True)

Order ID                      Product Name  Discount  Sales  \
41  AZ-2011-1536006   Logitech Keyboard, Programmable       0.0    666   
2   AZ-2011-1087704     Belkin Flash Drive, Bluetooth       0.0    294   
3   AZ-2011-1087704     Belkin Flash Drive, Bluetooth       0.0    294   
63  AZ-2011-1967754      Logitech Numeric Keypad, USB       0.0     93   
11  AZ-2011-1174243  Nokia Audio Dock, with Caller ID       0.0   1334   
23  AZ-2011-1322840  Motorola Headset, with Caller ID       0.0    957   
4   AZ-2011-1372644        Panasonic Printer, Durable       0.0    800   
5   AZ-2011-1372644        Panasonic Printer, Durable       0.0    800   
54  AZ-2011-1722024            Cisco Audio Dock, VoIP       0.0    364   
33  AZ-2011-1445262       Apple Smart Phone, Cordless       0.0    636   
30  AZ-2011-1410648      Nokia Smart Phone, Full Size       0.0   1908   

    Profit  Quantity    Category Sub-Category  order_len  Profit_per_qty  
41      66         9  Technology  Accessories         15        7.333333  
2      109         7  Technology  Accessories         15       15.571429  
3      109         7  Technology  Accessories         15       15.571429  
63      40         2  Technology  Accessories         15       20.000000  
11     200         8  Technology       Phones         15       25.000000  
23     316        12  Technology       Phones         15       26.333333  
4      168         3  Technology     Machines         15       56.000000  
5      168         3  Technology     Machines         15       56.000000  
54     142         2  Technology       Phones         15       71.000000  
33     140         1  Technology       Phones         15      140.000000  
30     820         3  Technology       Phones         15      273.333333